
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import py.com.systgastro.bean.dto.PedidoDTO;
import py.com.systgastro.model.jdbc.PedidoDAO;
import py.com.systgastro.model.jdbc.PedidoDaoJDBC;
import utilitarios.data;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import utilitarios.data;
import java.sql.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
import py.com.systgastro.model.jdbc.Conexion;


/**
 *
 * @author Alumnos de IS II
 * @version 1.0
 */
public class VentanaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipalView
     */
    data mostrar_datos;
    String set_look = "com.sun.java.swing.plaf.metal.MetalLookAndFeel";

    /**
     *
     */
    public VentanaPrincipalView() {
        initComponents();
        mostrar_datos = new data();
        mostrar_datos.el_dato();//primero ejecutar este método para después ejecutar el resto
        lbl_data.setText("Hoy es "+mostrar_datos.dia_semana+ " "+mostrar_datos.dia+" de "+mostrar_datos.mes+" del año "+mostrar_datos.anho);
        timer1.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        lbl_data = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        lbl_menu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cliente = new javax.swing.JMenu();
        miten_cambiarContraseña = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miten_salir = new javax.swing.JMenuItem();
        menu_movimientos = new javax.swing.JMenu();
        miten_ConsultarMenu = new javax.swing.JMenuItem();
        menu_pedido = new javax.swing.JMenu();
        miten_registrarPedido = new javax.swing.JMenuItem();
        miten_cosultarPedido = new javax.swing.JMenuItem();
        menu_facturacion = new javax.swing.JMenu();
        miten_obtenerFactura = new javax.swing.JMenuItem();
        menu_utilitarios = new javax.swing.JMenu();
        miten_lookNimbus = new javax.swing.JMenuItem();
        miten_lookLiquid = new javax.swing.JMenuItem();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gastronomico");

        lbl_data.setText("Fecha");

        lbl_hora.setText("Hora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_data)
                    .addComponent(lbl_hora))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_data)
                .addGap(18, 18, 18)
                .addComponent(lbl_hora))
        );

        lbl_menu.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\restaurante.png")); // NOI18N

        menu_cliente.setIcon(new javax.swing.ImageIcon("C:\\systvent\\systvent\\graficos\\clientes.png")); // NOI18N
        menu_cliente.setMnemonic('C');
        menu_cliente.setText("Cliente");

        miten_cambiarContraseña.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_cambiarContraseña.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\cargo.png")); // NOI18N
        miten_cambiarContraseña.setMnemonic('o');
        miten_cambiarContraseña.setText("Cambiar contraseña");
        menu_cliente.add(miten_cambiarContraseña);
        menu_cliente.add(jSeparator2);

        miten_salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_salir.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\salir.png")); // NOI18N
        miten_salir.setMnemonic('s');
        miten_salir.setText("Salir");
        miten_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_salirActionPerformed(evt);
            }
        });
        menu_cliente.add(miten_salir);

        jMenuBar1.add(menu_cliente);

        menu_movimientos.setIcon(new javax.swing.ImageIcon("C:\\systvent\\systvent\\graficos\\table.png")); // NOI18N
        menu_movimientos.setMnemonic('M');
        menu_movimientos.setText("Menú");

        miten_ConsultarMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        miten_ConsultarMenu.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\relatorio.png")); // NOI18N
        miten_ConsultarMenu.setText("Consultar menú");
        menu_movimientos.add(miten_ConsultarMenu);

        jMenuBar1.add(menu_movimientos);

        menu_pedido.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\pedido.jpg")); // NOI18N
        menu_pedido.setMnemonic('P');
        menu_pedido.setText("Pedido");

        miten_registrarPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        miten_registrarPedido.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\registrar_pedido.jpg")); // NOI18N
        miten_registrarPedido.setText("Registrar pedido");
        menu_pedido.add(miten_registrarPedido);

        miten_cosultarPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_cosultarPedido.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\consultar_pedido.png")); // NOI18N
        miten_cosultarPedido.setText("Consultar pedido");
        menu_pedido.add(miten_cosultarPedido);

        jMenuBar1.add(menu_pedido);

        menu_facturacion.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\factura.png")); // NOI18N
        menu_facturacion.setMnemonic('F');
        menu_facturacion.setText("Facturación");

        miten_obtenerFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_obtenerFactura.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\facturacion.png")); // NOI18N
        miten_obtenerFactura.setText("Obtener Factura");
        miten_obtenerFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_obtenerFacturaActionPerformed(evt);
            }
        });
        menu_facturacion.add(miten_obtenerFactura);

        jMenuBar1.add(menu_facturacion);

        menu_utilitarios.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\wrench_orange.png")); // NOI18N
        menu_utilitarios.setMnemonic('U');
        menu_utilitarios.setText("Utilitarios");

        miten_lookNimbus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_lookNimbus.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\application_double.png")); // NOI18N
        miten_lookNimbus.setText("Look and Fell-Nimbus");
        miten_lookNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_lookNimbusActionPerformed(evt);
            }
        });
        menu_utilitarios.add(miten_lookNimbus);

        miten_lookLiquid.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miten_lookLiquid.setIcon(new javax.swing.ImageIcon("C:\\systgastro\\systgastro\\graficos\\table.png")); // NOI18N
        miten_lookLiquid.setText("Look and Fell_Liquid");
        miten_lookLiquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miten_lookLiquidActionPerformed(evt);
            }
        });
        menu_utilitarios.add(miten_lookLiquid);

        jMenuBar1.add(menu_utilitarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_menu)
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 445, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
        mostrar_datos.leer_hora();
        lbl_hora.setText("Hora actual: "+mostrar_datos.hora);
    }//GEN-LAST:event_timer1OnTime

    private void miten_lookNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_lookNimbusActionPerformed
        // TODO add your handling code here:
        set_look = "javax.swing.plaf.metal.MetalLookAndFeel";
        lookandfeel();


    }//GEN-LAST:event_miten_lookNimbusActionPerformed

    private void miten_lookLiquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_lookLiquidActionPerformed
        // TODO add your handling code here:
        set_look = "com.birosoft.liquid.LiquidLookAndFeel";
        lookandfeel();

    }//GEN-LAST:event_miten_lookLiquidActionPerformed

    private void miten_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_salirActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_miten_salirActionPerformed

    private void miten_obtenerFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miten_obtenerFacturaActionPerformed
        Connection con;
        JasperReport reporte;
        try{
            con = (Connection) Conexion.getConnection();
            reporte = JasperCompileManager.compileReport("src/py/com/systgastro/reportes/Factura.jrxml");
            JasperPrint jp = JasperFillManager.fillReport(reporte, null, con);
            JasperViewer.viewReport(jp, true);
        }catch(SQLException | JRException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_miten_obtenerFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //Utilizamos el tipo interface como referencia
        //a una clase concreta
        //PedidoDAO pedidoDao = new PedidoDaoJDBC();
        /**
         * Creamos un nuevo registro 
         * Hacemos uso de la clase pedido DTO la cual se usa para transferir 
         * la información entre las capas 
         * no es necesario especificar la llave primaria ya que en este caso es 
         * de tipo autonumerico y la BD se encarga de asignarle un nuevo valor
         */
        /*PedidoDTO pedido = new PedidoDTO();
        
        pedido.setNombre_pedido("Hamburguesa");
        pedido.setFecha_pedido("2021-11-02");
        pedido.setNumero(1);
        pedido.setEstado("Pendiente");
        pedido.setCantidad(2);
        pedido.setTotal(20000);
        pedido.setCod_cliente(1);
        pedido.setCod_producto(4);*/

        //Utilizamos la capa DAO para persistir el objeto DTO
        /*try {

            pedidoDao.insert(pedido);
            //eliminamos un registro
            //pedidoDao.delete( new PedidoDTO(8));

            //actualizamos un registro
            //PedidoDTO pedidoTmp= new PedidoDTO();
            //pedidoTmp.setCod_pedido(3);
            //pedidoTmp.setNombre_pedido("Pizza Mozzarella");
            //pedidoTmp.setFecha_pedido("2021-11-02");
            //pedidoTmp.setNumero(1);
            //pedidoTmp.setEstado("Pendiente");
            //pedidoTmp.setCantidad(3);
            //pedidoTmp.setTotal(80000);
            //pedidoTmp.setCod_cliente(1);
            //pedidoTmp.setCod_producto(1);
            //pedidoDao.update(pedidoTmp);
            
            //Seleccionamos todos los registros
            List<PedidoDTO> pedidos = pedidoDao.select();
            for (PedidoDTO pedidoDTO : pedidos) {
                System.out.print(pedidoDTO);
                System.out.println();
            }
        } catch (SQLException e) {
            System.out.println("Excepcion en la capa de prueba");
            e.printStackTrace();
        }*/
        
        //Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JMenu menu_cliente;
    private javax.swing.JMenu menu_facturacion;
    private javax.swing.JMenu menu_movimientos;
    private javax.swing.JMenu menu_pedido;
    private javax.swing.JMenu menu_utilitarios;
    private javax.swing.JMenuItem miten_ConsultarMenu;
    private javax.swing.JMenuItem miten_cambiarContraseña;
    private javax.swing.JMenuItem miten_cosultarPedido;
    private javax.swing.JMenuItem miten_lookLiquid;
    private javax.swing.JMenuItem miten_lookNimbus;
    private javax.swing.JMenuItem miten_obtenerFactura;
    private javax.swing.JMenuItem miten_registrarPedido;
    private javax.swing.JMenuItem miten_salir;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void lookandfeel(){
        try{
            //La variable set look tiene que estar definida arriba como una variable String
            UIManager.setLookAndFeel(set_look);
            SwingUtilities.updateComponentTreeUI(this);
        }catch (Exception error){
            JOptionPane.showMessageDialog(null, error);
        }
    }
}
